// Authentication
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const RESET_AUTH_ERROR = 'RESET_AUTH_ERROR';
// Properties
export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_ERROR = 'FETCH_PROPERTIES_ERROR';
export const ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS';
export const ADD_PROPERTY_ERROR = 'ADD_PROPERTY_ERROR';
export const UPDATE_PROPERTY_SUCCESS = 'UPDATE_PROPERTY_SUCCESS';
export const UPDATE_PROPERTY_ERROR = 'UPDATE_PROPERTY_ERROR';
export const DELETE_PROPERTY_SUCCESS = 'DELETE_PROPERTY_SUCCESS';
export const DELETE_PROPERTY_ERROR = 'DELETE_PROPERTY_ERROR';
export const RESET_PROPERTY_ERROR = 'RESET_PROPERTY_ERROR';

// Offers
export const FETCH_OFFERS_SUCCESS = 'FETCH_OFFERS_SUCCESS';
export const FETCH_OFFERS_ERROR = 'FETCH_OFFERS_ERROR';
export const UPDATE_OFFER_STATUS_SUCCESS = 'UPDATE_OFFER_STATUS_SUCCESS';
export const UPDATE_OFFER_STATUS_ERROR = 'UPDATE_OFFER_STATUS_ERROR';
export const SUBMIT_OFFER_SUCCESS = 'SUBMIT_OFFER_SUCCESS';
export const SUBMIT_OFFER_ERROR = 'SUBMIT_OFFER_ERROR';

// Add more action types as needed for your app
